<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TargetSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('target')->insert([
            // ===== 3ID =====
            [
                'uuid'        => 'low_stock|3ID',
                'program'     => 'low_stock',
                'brand'       => '3ID',
                'target1'     => 5,
                'incentive1'  => 1000,
                'target2'     => 5,
                'incentive2'  => 200,
                'target3'     => 5,
                'incentive3'  => 300,
                'target4'     => 5,
                'incentive4'  => 400,
                'target5'     => 5,
                'incentive5'  => 500,
                'target6'     => 5,
                'incentive6'  => 600,
                'target7'     => 5,
                'incentive7'  => 700,
            ],
            [
                'uuid'        => 'low_productivity|3ID',
                'program'     => 'low_productivity',
                'brand'       => '3ID',
                'target1'     => 100000,
                'incentive1'  => 10000,
                'target2'     => 200000,
                'incentive2'  => 20000,
                'target3'     => 300000,
                'incentive3'  => 30000,
                'target4'     => 400000,
                'incentive4'  => 40000,
                'target5'     => 500000,
                'incentive5'  => 50000,
                'target6'     => 600000,
                'incentive6'  => 60000,
                'target7'     => 700000,
                'incentive7'  => 70000,
            ],
            [
                'uuid'        => 'high_productivity|3ID',
                'program'     => 'high_productivity',
                'brand'       => '3ID',
                'target1'     => 100000,
                'incentive1'  => 1000,
                'target2'     => 200000,
                'incentive2'  => 200,
                'target3'     => 300000,
                'incentive3'  => 300,
                'target4'     => 400000,
                'incentive4'  => 400,
                'target5'     => 500000,
                'incentive5'  => 500,
                'target6'     => 600000,
                'incentive6'  => 600,
                'target7'     => 700000,
                'incentive7'  => 700,
            ],
            [
                'uuid'        => 'ono|3ID',
                'program'     => 'ono',
                'brand'       => '3ID',
                'target1'     => 100000,
                'incentive1'  => 1000,
                'target2'     => 200000,
                'incentive2'  => 2000,
                'target3'     => 300000,
                'incentive3'  => 3000,
                'target4'     => 400000,
                'incentive4'  => 4000,
                'target5'     => 500000,
                'incentive5'  => 5000,
                'target6'     => 600000,
                'incentive6'  => 6000,
                'target7'     => 700000,
                'incentive7'  => 7000,
            ],

            // ===== IM3 =====
            [
                'uuid'        => 'low_stock|IM3',
                'program'     => 'low_stock',
                'brand'       => 'IM3',
                'target1'     => 5,
                'incentive1'  => 1000,
                'target2'     => 5,
                'incentive2'  => 200,
                'target3'     => 5,
                'incentive3'  => 300,
                'target4'     => 5,
                'incentive4'  => 400,
                'target5'     => 5,
                'incentive5'  => 500,
                'target6'     => 5,
                'incentive6'  => 600,
                'target7'     => 5,
                'incentive7'  => 700,
            ],
            [
                'uuid'        => 'low_productivity|IM3',
                'program'     => 'low_productivity',
                'brand'       => 'IM3',
                'target1'     => 100000,
                'incentive1'  => 1000,
                'target2'     => 200000,
                'incentive2'  => 200,
                'target3'     => 300000,
                'incentive3'  => 300,
                'target4'     => 400000,
                'incentive4'  => 400,
                'target5'     => 500000,
                'incentive5'  => 500,
                'target6'     => 600000,
                'incentive6'  => 600,
                'target7'     => 700000,
                'incentive7'  => 700,
            ],
            [
                'uuid'        => 'high_productivity|IM3',
                'program'     => 'high_productivity',
                'brand'       => 'IM3',
                'target1'     => 100000,
                'incentive1'  => 1000,
                'target2'     => 200000,
                'incentive2'  => 200,
                'target3'     => 300000,
                'incentive3'  => 300,
                'target4'     => 400000,
                'incentive4'  => 400,
                'target5'     => 500000,
                'incentive5'  => 500,
                'target6'     => 600000,
                'incentive6'  => 600,
                'target7'     => 700000,
                'incentive7'  => 700,
            ],
            [
                'uuid'        => 'ono|IM3',
                'program'     => 'ono',
                'brand'       => 'IM3',
                'target1'     => 100000,
                'incentive1'  => 1000,
                'target2'     => 200000,
                'incentive2'  => 200,
                'target3'     => 300000,
                'incentive3'  => 300,
                'target4'     => 400000,
                'incentive4'  => 400,
                'target5'     => 500000,
                'incentive5'  => 500,
                'target6'     => 600000,
                'incentive6'  => 600,
                'target7'     => 700000,
                'incentive7'  => 700,
            ],
        ]);
    }
}
